<?xml version="1.0" encoding="UTF-8"?>
<fpmd:simulation xmlns:fpmd="http://www.quantum-simulation.org/ns/fpmd/fpmd-1.0">

                   ============================
                   I qbox 1.63.7              I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I http://qboxcode.org      I
                   ============================


<release> 1.63.7 dogwood_mkl </release>
<user> yiy </user>
<sysname> Linux </sysname>
<nodename> dogwood-login1 </nodename>
<start_time> 2017-08-29T16:04:23Z </start_time>
<mpi_processes count="4">
<process id="0"> dogwood-login1 </process>
<process id="1"> dogwood-login1 </process>
<process id="2"> dogwood-login1 </process>
<process id="3"> dogwood-login1 </process>
</mpi_processes>
[qbox] <cmd>set cell 11 0 0  0 11 0  0 0 11</cmd>
<unit_cell 
    a="11.00000000  0.00000000   0.00000000  "
    b="0.00000000   11.00000000  0.00000000  "
    c="0.00000000   0.00000000   11.00000000 " />
[qbox] <cmd>species oxygen O_HSCV_PBE-1.0.xml</cmd>
  SpeciesCmd: defining species oxygen as O_HSCV_PBE-1.0.xml

 species oxygen:
<species name="oxygen">
 <description>
 PSGen-1.6.0 pseudopotential: HSCV O xc=PBE
 Generated by PSGen-1.6.0 on 2009-02-15T02:25:11Z
 psgen arguments:
 -element O -xc PBE -smooth_v -bound l=0:rc=0.8 -bound l=1:rc=0.8
 </description>
 <symbol>O</symbol>
 <atomic_number>8</atomic_number>
 <mass>15.99940000</mass>
 <norm_conserving_pseudopotential>
 <valence_charge>6</valence_charge>
 <lmax>1</lmax>
 <llocal>1</llocal>
 <nquad>0</nquad>
 <rquad>0.00000000</rquad>
 <mesh_spacing>0.01000000</mesh_spacing>
 </norm_conserving_pseudopotential>
</species>
 Kleinman-Bylander potential
 rcps_ =   1.50000000
[qbox] <cmd>atom O1 oxygen  1.16  0  0</cmd>
[qbox] <cmd>atom O2 oxygen -1.16  0  0</cmd>
[qbox] <cmd>set xc LIBXC GGA_X_PBE GGA_C_PBE</cmd>
[qbox] <cmd>#set xc PBE</cmd>
[qbox] <cmd>#set xc LIBXC GGA_X_B88 GGA_C_LYP</cmd>
[qbox] <cmd>#set xc BLYP</cmd>
[qbox] <cmd>set nspin 2</cmd>
[qbox] <cmd>set delta_spin 1</cmd>
[qbox] <cmd>set nempty 4</cmd>
[qbox] <cmd>set ecut 70</cmd>
[qbox] <cmd>set wf_dyn PSDA</cmd>
[qbox] <cmd>set ecutprec 5</cmd>
[qbox] <cmd>randomize_wf</cmd>
[qbox] <cmd>run 0 40 5 </cmd>
  EnergyFunctional: np0v,np1v,np2v: 64 64 64
  EnergyFunctional: vft->np012(): 262144
LIBXC
LIBXC
LIBXC
LIBXC
<wavefunction ecut="35.00000000" nspin="2" nel="12" nempty="4">
<cell a="11.000000 0.000000 0.000000"
      b="0.000000 11.000000 0.000000"
      c="0.000000 0.000000 11.000000"/>
 reciprocal lattice vectors
 0.571199 0.000000 0.000000
 0.000000 0.571199 0.000000
 0.000000 0.000000 0.571199
<refcell a="0.000000 0.000000 0.000000"
         b="0.000000 0.000000 0.000000"
         c="0.000000 0.000000 0.000000"/>
<grid nx="32" ny="32" nz="32"/>
 kpoint: 0.000000 0.000000 0.000000 weight: 1.000000
<slater_determinant kpoint="0.000000 0.000000 0.000000" size="11">
 sdcontext: 4x1
 basis size: 6603
 c dimensions: 6660x11   (1665x11 blocks)
 <density_matrix form="diagonal" size="11">
 </density_matrix>
</slater_determinant>
 kpoint: 0.000000 0.000000 0.000000 weight: 1.000000
<slater_determinant kpoint="0.000000 0.000000 0.000000" size="9">
 sdcontext: 4x1
 basis size: 6603
 c dimensions: 6660x9   (1665x9 blocks)
 <density_matrix form="diagonal" size="9">
 </density_matrix>
</slater_determinant>
</wavefunction>
<iteration count="1">
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
  <eigenvalue_sum>  205.15098807 </eigenvalue_sum>
  <eigenvalue_sum>  27.35407310 </eigenvalue_sum>
  Anderson extrapolation: theta=0.16017661 (0.16017661)
  Anderson extrapolation: theta=0.16211193 (0.16211193)
  <eigenvalue_sum>  -4.10726375 </eigenvalue_sum>
  Anderson extrapolation: theta=0.07083514 (0.07083514)
  Anderson extrapolation: theta=0.06429311 (0.06429311)
  <eigenvalue_sum>  -10.19411112 </eigenvalue_sum>
  Anderson extrapolation: theta=-0.35411363 (-0.35411363)
  Anderson extrapolation: theta=-0.23406945 (-0.23406945)
  <eigenvalue_sum>  -13.20334518 </eigenvalue_sum>
  Anderson extrapolation: theta=-2.34879343 (0.00000000)
  Anderson extrapolation: theta=-1.87953530 (0.00000000)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
  -118.06181   -52.64576   -39.38208   -34.24917   -18.49397
   -13.05013   -10.46882    -1.77375     6.52726     7.83898
     8.54774
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
  -118.11124   -49.31255   -35.65318   -20.57571   -15.65700
   -11.82587    -4.35176     4.06026     7.10126
  </eigenvalues>
</eigenset>
  <etotal_int>     -22.75863785 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
  <eigenvalue_sum>  -17.16842190 </eigenvalue_sum>
  <eigenvalue_sum>  -23.23301082 </eigenvalue_sum>
  Anderson extrapolation: theta=-1.06285031 (0.00000000)
  Anderson extrapolation: theta=-1.15625459 (0.00000000)
  <eigenvalue_sum>  -30.06800064 </eigenvalue_sum>
  Anderson extrapolation: theta=-0.29525782 (-0.29525782)
  Anderson extrapolation: theta=-0.72610801 (-0.72610801)
  <eigenvalue_sum>  -33.41939310 </eigenvalue_sum>
  Anderson extrapolation: theta=0.25627781 (0.25627781)
  Anderson extrapolation: theta=-1.09911969 (0.00000000)
  <eigenvalue_sum>  -40.06333721 </eigenvalue_sum>
  Anderson extrapolation: theta=0.01099007 (0.01099007)
  Anderson extrapolation: theta=-0.14358120 (-0.14358120)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
  -120.59504  -102.99520   -91.84671   -87.80900   -85.82415
   -77.21541   -32.44515   -25.43631   -20.00400   -16.44363
     4.86422
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
  -119.42757   -98.33299   -87.17723   -79.25316   -69.52403
   -49.24606   -33.79841   -17.80052    -9.04157
  </eigenvalues>
</eigenset>
  <etotal_int>     -41.93759903 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.86157429 
  <eigenvalue_sum>  -43.25606865 </eigenvalue_sum>
  <eigenvalue_sum>  -47.27197961 </eigenvalue_sum>
  Anderson extrapolation: theta=0.30575008 (0.30575008)
  Anderson extrapolation: theta=0.21416317 (0.21416317)
  <eigenvalue_sum>  -51.03112618 </eigenvalue_sum>
  Anderson extrapolation: theta=0.52877285 (0.52877285)
  Anderson extrapolation: theta=0.53673375 (0.53673375)
  <eigenvalue_sum>  -53.59156407 </eigenvalue_sum>
  Anderson extrapolation: theta=0.09122547 (0.09122547)
  Anderson extrapolation: theta=0.12351925 (0.12351925)
  <eigenvalue_sum>  -54.48048814 </eigenvalue_sum>
  Anderson extrapolation: theta=0.37961423 (0.37961423)
  Anderson extrapolation: theta=0.62456019 (0.62456019)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
  -117.52394  -100.13712   -94.81845   -94.25416   -92.12149
   -86.23791   -84.97740   -40.30874   -32.38918   -28.35353
    -1.38823
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
  -116.95271   -99.37254   -92.71776   -92.62482   -91.90350
   -85.77051   -85.41806   -39.19594   -31.45118
  </eigenvalues>
</eigenset>
  <etotal_int>     -46.37816583 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.40171613 0.80320651 
  <eigenvalue_sum>  -55.33463457 </eigenvalue_sum>
  <eigenvalue_sum>  -55.88925682 </eigenvalue_sum>
  Anderson extrapolation: theta=-1.92278227 (0.00000000)
  Anderson extrapolation: theta=-1.00308390 (0.00000000)
  <eigenvalue_sum>  -56.48111572 </eigenvalue_sum>
  Anderson extrapolation: theta=-1.88804397 (0.00000000)
  Anderson extrapolation: theta=-1.09818711 (0.00000000)
  <eigenvalue_sum>  -57.09638028 </eigenvalue_sum>
  Anderson extrapolation: theta=-0.86746920 (-0.86746920)
  Anderson extrapolation: theta=-0.15974135 (-0.15974135)
  <eigenvalue_sum>  -57.35791092 </eigenvalue_sum>
  Anderson extrapolation: theta=2.43207310 (2.00000000)
  Anderson extrapolation: theta=1.93926213 (1.93926213)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
  -118.15084  -100.31982   -95.89279   -95.11790   -92.09609
   -85.02121   -83.68506   -67.06393   -33.35453   -29.56196
    -9.88659
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
  -117.23758   -99.42962   -93.34177   -92.77533   -92.10263
   -85.82554   -85.43624   -75.45889   -33.15348
  </eigenvalues>
</eigenset>
  <etotal_int>     -46.41754475 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.33193431 0.38919108 0.80684076 
  <eigenvalue_sum>  -58.25253826 </eigenvalue_sum>
  <eigenvalue_sum>  -58.59631564 </eigenvalue_sum>
  Anderson extrapolation: theta=2.08303889 (2.00000000)
  Anderson extrapolation: theta=2.74761621 (2.00000000)
  <eigenvalue_sum>  -59.18457460 </eigenvalue_sum>
  Anderson extrapolation: theta=0.10952766 (0.10952766)
  Anderson extrapolation: theta=0.14807102 (0.14807102)
  <eigenvalue_sum>  -59.29409165 </eigenvalue_sum>
  Anderson extrapolation: theta=1.51954679 (1.51954679)
  Anderson extrapolation: theta=0.50333899 (0.50333899)
  <eigenvalue_sum>  -59.45012262 </eigenvalue_sum>
  Anderson extrapolation: theta=0.32918067 (0.32918067)
  Anderson extrapolation: theta=0.87932675 (0.87932675)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
  -118.15795  -100.32916   -95.90814   -95.12272   -92.32944
   -85.09209   -83.99028   -79.88030   -33.73483   -29.87207
   -25.70114
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
  -117.25348   -99.46905   -93.33610   -92.78689   -92.19211
   -85.90309   -85.55910   -79.40495   -33.44431
  </eigenvalues>
</eigenset>
  <etotal_int>     -46.44370127 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.02649648 0.13346285 0.95026338 
  <eigenvalue_sum>  -42.68169972 </eigenvalue_sum>
  <eigenvalue_sum>  -42.84141308 </eigenvalue_sum>
  Anderson extrapolation: theta=1.66560145 (1.66560145)
  Anderson extrapolation: theta=1.53663710 (1.53663710)
  <eigenvalue_sum>  -43.00706215 </eigenvalue_sum>
  Anderson extrapolation: theta=0.22645252 (0.22645252)
  Anderson extrapolation: theta=0.17094598 (0.17094598)
  <eigenvalue_sum>  -43.03878624 </eigenvalue_sum>
  Anderson extrapolation: theta=1.34477048 (1.34477048)
  Anderson extrapolation: theta=1.04343441 (1.04343441)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -92.14557   -76.09497   -69.94651   -69.78113   -68.64460
   -63.01552   -62.52330   -54.98700   -19.56513   -15.07827
   -14.16273
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -90.97603   -75.00090   -68.03155   -67.93917   -67.86690
   -62.05556   -61.43095   -54.15296   -18.73482
  </eigenvalues>
</eigenset>
  <etotal_int>     -39.31622584 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.54161408 -0.52601778 -0.58466505 
  <eigenvalue_sum>  -9.29582034 </eigenvalue_sum>
  <eigenvalue_sum>  -10.17481723 </eigenvalue_sum>
  Anderson extrapolation: theta=1.99067500 (1.99067500)
  Anderson extrapolation: theta=1.96033619 (1.96033619)
  <eigenvalue_sum>  -11.37435187 </eigenvalue_sum>
  Anderson extrapolation: theta=0.20510167 (0.20510167)
  Anderson extrapolation: theta=0.18978589 (0.18978589)
  <eigenvalue_sum>  -11.59562757 </eigenvalue_sum>
  Anderson extrapolation: theta=1.23501651 (1.23501651)
  Anderson extrapolation: theta=1.26889053 (1.26889053)
  <eigenvalue_sum>  -11.83703092 </eigenvalue_sum>
  Anderson extrapolation: theta=0.43319315 (0.43319315)
  Anderson extrapolation: theta=0.34800201 (0.34800201)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -42.26060   -28.96520   -22.24028   -22.21712   -21.56507
   -15.12641   -15.05376    -4.30238    -1.03823     4.00295
     4.22662
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -40.95602   -27.53103   -20.93489   -20.68991   -20.26391
   -13.30341   -12.92060    -3.22199    -0.71780
  </eigenvalues>
</eigenset>
  <etotal_int>     -32.27075857 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.23642780 0.12284960 0.08170574 
  <eigenvalue_sum>  -12.33714334 </eigenvalue_sum>
  <eigenvalue_sum>  -12.39441460 </eigenvalue_sum>
  Anderson extrapolation: theta=2.91638590 (2.00000000)
  Anderson extrapolation: theta=2.45825911 (2.00000000)
  <eigenvalue_sum>  -12.51167456 </eigenvalue_sum>
  Anderson extrapolation: theta=0.62946125 (0.62946125)
  Anderson extrapolation: theta=0.35244606 (0.35244606)
  <eigenvalue_sum>  -12.58283802 </eigenvalue_sum>
  Anderson extrapolation: theta=0.91001989 (0.91001989)
  Anderson extrapolation: theta=1.22529606 (1.22529606)
  <eigenvalue_sum>  -12.65738415 </eigenvalue_sum>
  Anderson extrapolation: theta=1.10925406 (1.10925406)
  Anderson extrapolation: theta=0.97876859 (0.97876859)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -42.90939   -30.16581   -22.99252   -22.97992   -22.80872
   -16.32170   -16.28646    -5.58827    -2.41700     1.75871
     3.40738
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -41.66799   -28.54170   -22.09022   -21.20327   -20.99036
   -14.15966   -13.96361    -4.58924    -1.95542
  </eigenvalues>
</eigenset>
  <etotal_int>     -32.11175331 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.71230603 -0.56746695 0.23312292 
  <eigenvalue_sum>  -6.77479838 </eigenvalue_sum>
  <eigenvalue_sum>  -6.83857406 </eigenvalue_sum>
  Anderson extrapolation: theta=2.84166756 (2.00000000)
  Anderson extrapolation: theta=2.84048918 (2.00000000)
  <eigenvalue_sum>  -6.96903646 </eigenvalue_sum>
  Anderson extrapolation: theta=0.54892295 (0.54892295)
  Anderson extrapolation: theta=0.54398252 (0.54398252)
  <eigenvalue_sum>  -7.04443092 </eigenvalue_sum>
  Anderson extrapolation: theta=0.80364161 (0.80364161)
  Anderson extrapolation: theta=0.74794368 (0.74794368)
  <eigenvalue_sum>  -7.11141450 </eigenvalue_sum>
  Anderson extrapolation: theta=1.08813790 (1.08813790)
  Anderson extrapolation: theta=1.05761824 (1.05761824)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -32.81641   -21.22275   -13.96689   -13.95632   -13.89967
    -7.37976    -7.34550    -1.33741     2.70776     3.27052
     5.02805
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -31.52405   -19.39427   -13.15546   -11.98191   -11.94243
    -4.94951    -4.91050    -0.93828     4.22769
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.81756242 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.81605183 -0.52872061 -0.05677196 
  <eigenvalue_sum>  -7.28212488 </eigenvalue_sum>
  <eigenvalue_sum>  -7.29915773 </eigenvalue_sum>
  Anderson extrapolation: theta=2.89133190 (2.00000000)
  Anderson extrapolation: theta=2.69858548 (2.00000000)
  <eigenvalue_sum>  -7.33963162 </eigenvalue_sum>
  Anderson extrapolation: theta=0.70496399 (0.70496399)
  Anderson extrapolation: theta=0.59424668 (0.59424668)
  <eigenvalue_sum>  -7.37246127 </eigenvalue_sum>
  Anderson extrapolation: theta=1.01327434 (1.01327434)
  Anderson extrapolation: theta=1.14549901 (1.14549901)
  <eigenvalue_sum>  -7.41132935 </eigenvalue_sum>
  Anderson extrapolation: theta=1.20941088 (1.20941088)
  Anderson extrapolation: theta=1.15734380 (1.15734380)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.16844   -21.44419   -14.17792   -14.13898   -14.11308
    -7.69893    -7.67768    -2.04438     2.17810     2.71235
     4.04687
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -31.88855   -19.55246   -13.36521   -12.14014   -12.08603
    -5.18301    -5.12513    -1.73084     3.66072
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.80451764 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.01726372 0.00924594 -0.06025478 
  <eigenvalue_sum>  -7.32580505 </eigenvalue_sum>
  <eigenvalue_sum>  -7.33301863 </eigenvalue_sum>
  Anderson extrapolation: theta=3.13703639 (2.00000000)
  Anderson extrapolation: theta=3.00688896 (2.00000000)
  <eigenvalue_sum>  -7.35157203 </eigenvalue_sum>
  Anderson extrapolation: theta=0.90201881 (0.90201881)
  Anderson extrapolation: theta=0.83724451 (0.83724451)
  <eigenvalue_sum>  -7.37099900 </eigenvalue_sum>
  Anderson extrapolation: theta=1.09759089 (1.09759089)
  Anderson extrapolation: theta=1.04544955 (1.04544955)
  <eigenvalue_sum>  -7.39407635 </eigenvalue_sum>
  Anderson extrapolation: theta=1.52281551 (1.52281551)
  Anderson extrapolation: theta=1.29700096 (1.29700096)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.04008   -21.24442   -14.00294   -13.96119   -13.94869
    -7.51851    -7.50439    -2.17249     2.12417     2.62698
     3.01719
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -31.75247   -19.34109   -13.16585   -11.95075   -11.90796
    -5.00346    -4.95788    -1.93028     3.56463
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.80807648 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.23503756 -0.37313515 0.01575963 
  <eigenvalue_sum>  -7.49574960 </eigenvalue_sum>
  <eigenvalue_sum>  -7.49950129 </eigenvalue_sum>
  Anderson extrapolation: theta=2.59088628 (2.00000000)
  Anderson extrapolation: theta=2.25374182 (2.00000000)
  <eigenvalue_sum>  -7.50772542 </eigenvalue_sum>
  Anderson extrapolation: theta=0.59380405 (0.59380405)
  Anderson extrapolation: theta=0.34628218 (0.34628218)
  <eigenvalue_sum>  -7.51323145 </eigenvalue_sum>
  Anderson extrapolation: theta=1.33560327 (1.33560327)
  Anderson extrapolation: theta=1.46895981 (1.46895981)
  <eigenvalue_sum>  -7.52148395 </eigenvalue_sum>
  Anderson extrapolation: theta=1.11155952 (1.11155952)
  Anderson extrapolation: theta=0.62937271 (0.62937271)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.26724   -21.38897   -14.17334   -14.10525   -14.10230
    -7.68087    -7.67456    -2.00174     2.24331     2.42231
     2.69189
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -31.98485   -19.49119   -13.31698   -12.09904   -12.07309
    -5.16958    -5.14432    -1.81630     3.23234
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.81397787 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.07182254 -0.74507841 0.18610097 
  <eigenvalue_sum>  -7.48874272 </eigenvalue_sum>
  <eigenvalue_sum>  -7.49168753 </eigenvalue_sum>
  Anderson extrapolation: theta=2.45670867 (2.00000000)
  Anderson extrapolation: theta=2.13220490 (2.00000000)
  <eigenvalue_sum>  -7.49750916 </eigenvalue_sum>
  Anderson extrapolation: theta=0.47775950 (0.47775950)
  Anderson extrapolation: theta=0.32704241 (0.32704241)
  <eigenvalue_sum>  -7.50065465 </eigenvalue_sum>
  Anderson extrapolation: theta=1.29331152 (1.29331152)
  Anderson extrapolation: theta=2.01552486 (2.00000000)
  <eigenvalue_sum>  -7.50556941 </eigenvalue_sum>
  Anderson extrapolation: theta=0.77135530 (0.77135530)
  Anderson extrapolation: theta=0.49255087 (0.49255087)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.33182   -21.39745   -14.20614   -14.12360   -14.12032
    -7.69738    -7.69512    -1.56715     2.14971     2.71488
     2.86353
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.05085   -19.50930   -13.33647   -12.11563   -12.11150
    -5.20057    -5.19699    -1.42865     3.02527
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82003120 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.46388160 -0.25846844 0.34554159 
  <eigenvalue_sum>  -7.53821524 </eigenvalue_sum>
  <eigenvalue_sum>  -7.53946161 </eigenvalue_sum>
  Anderson extrapolation: theta=2.04767058 (2.00000000)
  Anderson extrapolation: theta=1.87555430 (1.87555430)
  <eigenvalue_sum>  -7.54228879 </eigenvalue_sum>
  Anderson extrapolation: theta=0.33358744 (0.33358744)
  Anderson extrapolation: theta=0.28797867 (0.28797867)
  <eigenvalue_sum>  -7.54387024 </eigenvalue_sum>
  Anderson extrapolation: theta=3.07016195 (2.00000000)
  Anderson extrapolation: theta=3.49082705 (2.00000000)
  <eigenvalue_sum>  -7.54751054 </eigenvalue_sum>
  Anderson extrapolation: theta=1.38461100 (1.38461100)
  Anderson extrapolation: theta=1.76716348 (1.76716348)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.28623   -21.37506   -14.18010   -14.10596   -14.10504
    -7.66971    -7.66913    -1.81650     2.02485     2.39932
     2.54261
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.00889   -19.49914   -13.32185   -12.10751   -12.10665
    -5.18924    -5.18853    -1.67613     2.80612
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82057125 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.35420056 -0.09530213 -0.03153477 
  <eigenvalue_sum>  -7.54407257 </eigenvalue_sum>
  <eigenvalue_sum>  -7.54526103 </eigenvalue_sum>
  Anderson extrapolation: theta=2.48836495 (2.00000000)
  Anderson extrapolation: theta=2.57841832 (2.00000000)
  <eigenvalue_sum>  -7.54790117 </eigenvalue_sum>
  Anderson extrapolation: theta=0.54776411 (0.54776411)
  Anderson extrapolation: theta=0.60457637 (0.60457637)
  <eigenvalue_sum>  -7.54975614 </eigenvalue_sum>
  Anderson extrapolation: theta=1.42884691 (1.42884691)
  Anderson extrapolation: theta=1.35762533 (1.35762533)
  <eigenvalue_sum>  -7.55249298 </eigenvalue_sum>
  Anderson extrapolation: theta=0.82893604 (0.82893604)
  Anderson extrapolation: theta=0.95661486 (0.95661486)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.33687   -21.40923   -14.21810   -14.13951   -14.13828
    -7.70649    -7.70552    -1.59299     1.98082     2.52064
     2.59215
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.06086   -19.53344   -13.35746   -12.13998   -12.13920
    -5.22601    -5.22503    -1.45350     2.70617
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82123056 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.07408886 -0.29632096 -0.01442246 
  <eigenvalue_sum>  -7.56760733 </eigenvalue_sum>
  <eigenvalue_sum>  -7.56858160 </eigenvalue_sum>
  Anderson extrapolation: theta=2.12155035 (2.00000000)
  Anderson extrapolation: theta=2.27603651 (2.00000000)
  <eigenvalue_sum>  -7.57080990 </eigenvalue_sum>
  Anderson extrapolation: theta=0.48966776 (0.48966776)
  Anderson extrapolation: theta=0.62298877 (0.62298877)
  <eigenvalue_sum>  -7.57240923 </eigenvalue_sum>
  Anderson extrapolation: theta=2.92913492 (2.00000000)
  Anderson extrapolation: theta=2.49559239 (2.00000000)
  <eigenvalue_sum>  -7.57557288 </eigenvalue_sum>
  Anderson extrapolation: theta=1.24931218 (1.24931218)
  Anderson extrapolation: theta=1.17749734 (1.17749734)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.32928   -21.40542   -14.21406   -14.13775   -14.13750
    -7.70239    -7.70204    -1.64805     1.91593     2.36320
     2.39098
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.05537   -19.53330   -13.35638   -12.14202   -12.14071
    -5.22745    -5.22606    -1.52065     2.57747
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82158707 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.74340660 -0.07566807 -0.15535982 
  <eigenvalue_sum>  -7.58160701 </eigenvalue_sum>
  <eigenvalue_sum>  -7.58192182 </eigenvalue_sum>
  Anderson extrapolation: theta=3.69155260 (2.00000000)
  Anderson extrapolation: theta=3.77469497 (2.00000000)
  <eigenvalue_sum>  -7.58274241 </eigenvalue_sum>
  Anderson extrapolation: theta=1.27720507 (1.27720507)
  Anderson extrapolation: theta=1.28901706 (1.28901706)
  <eigenvalue_sum>  -7.58386727 </eigenvalue_sum>
  Anderson extrapolation: theta=0.88073273 (0.88073273)
  Anderson extrapolation: theta=0.88552939 (0.88552939)
  <eigenvalue_sum>  -7.58491300 </eigenvalue_sum>
  Anderson extrapolation: theta=1.49890536 (1.49890536)
  Anderson extrapolation: theta=1.77397230 (1.77397230)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.33952   -21.41411   -14.22290   -14.14588   -14.14570
    -7.71132    -7.71106    -1.62856     1.89348     2.35256
     2.35641
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.06580   -19.54161   -13.36495   -12.14952   -12.14851
    -5.23546    -5.23436    -1.50166     2.51799
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82161175 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.10398877 -0.25414554 0.06715662 
  <eigenvalue_sum>  -7.60160899 </eigenvalue_sum>
  <eigenvalue_sum>  -7.60189487 </eigenvalue_sum>
  Anderson extrapolation: theta=2.44988959 (2.00000000)
  Anderson extrapolation: theta=2.68830177 (2.00000000)
  <eigenvalue_sum>  -7.60252167 </eigenvalue_sum>
  Anderson extrapolation: theta=0.47700369 (0.47700369)
  Anderson extrapolation: theta=0.61061335 (0.61061335)
  <eigenvalue_sum>  -7.60294601 </eigenvalue_sum>
  Anderson extrapolation: theta=1.27823431 (1.27823431)
  Anderson extrapolation: theta=1.09072210 (1.09072210)
  <eigenvalue_sum>  -7.60350839 </eigenvalue_sum>
  Anderson extrapolation: theta=0.70292424 (0.70292424)
  Anderson extrapolation: theta=0.98902396 (0.98902396)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.33577   -21.41160   -14.21985   -14.14430   -14.14422
    -7.70923    -7.70914    -1.70452     1.85923     2.19455
     2.26168
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.06289   -19.53963   -13.36303   -12.14826   -12.14777
    -5.23367    -5.23314    -1.58159     2.45496
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82166714 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.02594888 -0.89718763 0.15303342 
  <eigenvalue_sum>  -7.62242473 </eigenvalue_sum>
  <eigenvalue_sum>  -7.62266049 </eigenvalue_sum>
  Anderson extrapolation: theta=2.31926854 (2.00000000)
  Anderson extrapolation: theta=2.45921725 (2.00000000)
  <eigenvalue_sum>  -7.62319797 </eigenvalue_sum>
  Anderson extrapolation: theta=0.46718791 (0.46718791)
  Anderson extrapolation: theta=0.66166321 (0.66166321)
  <eigenvalue_sum>  -7.62358398 </eigenvalue_sum>
  Anderson extrapolation: theta=1.76389769 (1.76389769)
  Anderson extrapolation: theta=1.75127675 (1.75127675)
  <eigenvalue_sum>  -7.62427627 </eigenvalue_sum>
  Anderson extrapolation: theta=0.58041862 (0.58041862)
  Anderson extrapolation: theta=0.73471413 (0.73471413)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.34278   -21.41825   -14.22638   -14.15048   -14.15040
    -7.71624    -7.71615    -1.77911     1.81829     2.04659
     2.18182
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.07020   -19.54571   -13.36957   -12.15379   -12.15365
    -5.23932    -5.23920    -1.64632     2.38890
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82168596 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.65439311 0.27254249 -0.41245614 
  <eigenvalue_sum>  -7.62278479 </eigenvalue_sum>
  <eigenvalue_sum>  -7.62288021 </eigenvalue_sum>
  Anderson extrapolation: theta=2.72617732 (2.00000000)
  Anderson extrapolation: theta=2.87186320 (2.00000000)
  <eigenvalue_sum>  -7.62313465 </eigenvalue_sum>
  Anderson extrapolation: theta=0.63871846 (0.63871846)
  Anderson extrapolation: theta=0.78165562 (0.78165562)
  <eigenvalue_sum>  -7.62337439 </eigenvalue_sum>
  Anderson extrapolation: theta=1.35001217 (1.35001217)
  Anderson extrapolation: theta=1.33708401 (1.33708401)
  <eigenvalue_sum>  -7.62374210 </eigenvalue_sum>
  Anderson extrapolation: theta=1.29580785 (1.29580785)
  Anderson extrapolation: theta=1.44670192 (1.44670192)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.34321   -21.41850   -14.22665   -14.15082   -14.15075
    -7.71644    -7.71637    -1.76527     1.81351     2.04977
     2.18587
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.07070   -19.54615   -13.36991   -12.15421   -12.15419
    -5.23974    -5.23972    -1.63133     2.37646
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82168430 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.11136126 -0.65204600 0.23484487 
  <eigenvalue_sum>  -7.62786204 </eigenvalue_sum>
  <eigenvalue_sum>  -7.62792465 </eigenvalue_sum>
  Anderson extrapolation: theta=2.48147643 (2.00000000)
  Anderson extrapolation: theta=3.47772242 (2.00000000)
  <eigenvalue_sum>  -7.62809217 </eigenvalue_sum>
  Anderson extrapolation: theta=0.53579505 (0.53579505)
  Anderson extrapolation: theta=0.95589364 (0.95589364)
  <eigenvalue_sum>  -7.62825332 </eigenvalue_sum>
  Anderson extrapolation: theta=1.58808740 (1.58808740)
  Anderson extrapolation: theta=0.75799603 (0.75799603)
  <eigenvalue_sum>  -7.62847105 </eigenvalue_sum>
  Anderson extrapolation: theta=1.01668947 (1.01668947)
  Anderson extrapolation: theta=1.94399038 (1.94399038)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.34868   -21.42333   -14.23158   -14.15521   -14.15520
    -7.72124    -7.72121    -1.77220     1.80213     2.04219
     2.17367
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.07608   -19.55063   -13.37451   -12.15838   -12.15831
    -5.24405    -5.24399    -1.63582     2.36086
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82168626 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.08105627 -0.42912381 -0.05677460 
  <eigenvalue_sum>  -7.63253147 </eigenvalue_sum>
  <eigenvalue_sum>  -7.63257433 </eigenvalue_sum>
  Anderson extrapolation: theta=2.76820381 (2.00000000)
  Anderson extrapolation: theta=3.64326260 (2.00000000)
  <eigenvalue_sum>  -7.63269512 </eigenvalue_sum>
  Anderson extrapolation: theta=1.11060630 (1.11060630)
  Anderson extrapolation: theta=1.33964641 (1.33964641)
  <eigenvalue_sum>  -7.63286874 </eigenvalue_sum>
  Anderson extrapolation: theta=2.06439314 (2.00000000)
  Anderson extrapolation: theta=1.06603342 (1.06603342)
  <eigenvalue_sum>  -7.63316181 </eigenvalue_sum>
  Anderson extrapolation: theta=1.25762696 (1.25762696)
  Anderson extrapolation: theta=1.93133290 (1.93133290)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35214   -21.42641   -14.23472   -14.15811   -14.15810
    -7.72427    -7.72427    -1.78354     1.78950     2.02507
     2.15416
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.07951   -19.55362   -13.37752   -12.16119   -12.16115
    -5.24692    -5.24689    -1.64679     2.34466
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82168743 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.32998653 -0.60049297 0.70006924 
  <eigenvalue_sum>  -7.63827751 </eigenvalue_sum>
  <eigenvalue_sum>  -7.63831728 </eigenvalue_sum>
  Anderson extrapolation: theta=2.18883092 (2.00000000)
  Anderson extrapolation: theta=2.56817978 (2.00000000)
  <eigenvalue_sum>  -7.63841667 </eigenvalue_sum>
  Anderson extrapolation: theta=0.37733105 (0.37733105)
  Anderson extrapolation: theta=0.53358403 (0.53358403)
  <eigenvalue_sum>  -7.63848365 </eigenvalue_sum>
  Anderson extrapolation: theta=2.03593379 (2.00000000)
  Anderson extrapolation: theta=1.10032962 (1.10032962)
  <eigenvalue_sum>  -7.63861427 </eigenvalue_sum>
  Anderson extrapolation: theta=0.63781775 (0.63781775)
  Anderson extrapolation: theta=0.96484959 (0.96484959)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35315   -21.42741   -14.23571   -14.15905   -14.15904
    -7.72527    -7.72526    -1.81077     1.77766     2.00627
     2.12805
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08044   -19.55450   -13.37845   -12.16204   -12.16197
    -5.24778    -5.24771    -1.67290     2.32745
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82168935 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.23617011 -0.92049935 0.00610593 
  <eigenvalue_sum>  -7.64734237 </eigenvalue_sum>
  <eigenvalue_sum>  -7.64739595 </eigenvalue_sum>
  Anderson extrapolation: theta=2.69176043 (2.00000000)
  Anderson extrapolation: theta=2.66767422 (2.00000000)
  <eigenvalue_sum>  -7.64752973 </eigenvalue_sum>
  Anderson extrapolation: theta=0.68903772 (0.68903772)
  Anderson extrapolation: theta=0.72869312 (0.72869312)
  <eigenvalue_sum>  -7.64764735 </eigenvalue_sum>
  Anderson extrapolation: theta=1.33152346 (1.33152346)
  Anderson extrapolation: theta=1.64884020 (1.64884020)
  <eigenvalue_sum>  -7.64782743 </eigenvalue_sum>
  Anderson extrapolation: theta=0.95469300 (0.95469300)
  Anderson extrapolation: theta=1.10124970 (1.10124970)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35750   -21.43136   -14.23972   -14.16278   -14.16276
    -7.72917    -7.72915    -1.85913     1.75849     1.97670
     2.08802
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08467   -19.55826   -13.38225   -12.16558   -12.16555
    -5.25139    -5.25135    -1.71001     2.30283
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169054 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.83145593 0.17571691 -0.35276604 
  <eigenvalue_sum>  -7.64548345 </eigenvalue_sum>
  <eigenvalue_sum>  -7.64551010 </eigenvalue_sum>
  Anderson extrapolation: theta=2.64519077 (2.00000000)
  Anderson extrapolation: theta=2.49710259 (2.00000000)
  <eigenvalue_sum>  -7.64557829 </eigenvalue_sum>
  Anderson extrapolation: theta=0.44288311 (0.44288311)
  Anderson extrapolation: theta=0.39193343 (0.39193343)
  <eigenvalue_sum>  -7.64562466 </eigenvalue_sum>
  Anderson extrapolation: theta=0.92857307 (0.92857307)
  Anderson extrapolation: theta=1.32264362 (1.32264362)
  <eigenvalue_sum>  -7.64568879 </eigenvalue_sum>
  Anderson extrapolation: theta=1.06200880 (1.06200880)
  Anderson extrapolation: theta=1.08514628 (1.08514628)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35630   -21.43028   -14.23862   -14.16176   -14.16175
    -7.72809    -7.72808    -1.84458     1.76228     1.98264
     2.09358
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08349   -19.55724   -13.38121   -12.16462   -12.16459
    -5.25040    -5.25037    -1.69829     2.30746
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169044 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.63213040 -0.35227867 0.01060950 
  <eigenvalue_sum>  -7.64647241 </eigenvalue_sum>
  <eigenvalue_sum>  -7.64649072 </eigenvalue_sum>
  Anderson extrapolation: theta=2.95616519 (2.00000000)
  Anderson extrapolation: theta=3.25161696 (2.00000000)
  <eigenvalue_sum>  -7.64654346 </eigenvalue_sum>
  Anderson extrapolation: theta=0.79577167 (0.79577167)
  Anderson extrapolation: theta=0.97227340 (0.97227340)
  <eigenvalue_sum>  -7.64660269 </eigenvalue_sum>
  Anderson extrapolation: theta=1.32807659 (1.32807659)
  Anderson extrapolation: theta=1.33182971 (1.33182971)
  <eigenvalue_sum>  -7.64669515 </eigenvalue_sum>
  Anderson extrapolation: theta=1.65778453 (1.65778453)
  Anderson extrapolation: theta=2.21150097 (2.00000000)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35685   -21.43075   -14.23910   -14.16225   -14.16225
    -7.72855    -7.72854    -1.84776     1.75928     1.98269
     2.08498
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08402   -19.55773   -13.38168   -12.16510   -12.16510
    -5.25089    -5.25088    -1.70166     2.30280
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169054 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.05449663 -0.55071981 -0.01967882 
  <eigenvalue_sum>  -7.64632299 </eigenvalue_sum>
  <eigenvalue_sum>  -7.64633787 </eigenvalue_sum>
  Anderson extrapolation: theta=2.90781987 (2.00000000)
  Anderson extrapolation: theta=3.12852806 (2.00000000)
  <eigenvalue_sum>  -7.64638054 </eigenvalue_sum>
  Anderson extrapolation: theta=0.58972957 (0.58972957)
  Anderson extrapolation: theta=0.64892435 (0.64892435)
  <eigenvalue_sum>  -7.64641888 </eigenvalue_sum>
  Anderson extrapolation: theta=0.94317388 (0.94317388)
  Anderson extrapolation: theta=0.82084833 (0.82084833)
  <eigenvalue_sum>  -7.64646712 </eigenvalue_sum>
  Anderson extrapolation: theta=1.72347980 (1.72347980)
  Anderson extrapolation: theta=2.21649572 (2.00000000)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35654   -21.43050   -14.23884   -14.16203   -14.16203
    -7.72829    -7.72829    -1.84441     1.75922     1.98602
     2.08276
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08372   -19.55753   -13.38146   -12.16491   -12.16491
    -5.25070    -5.25069    -1.70048     2.30211
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169052 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.32454617 -0.15737232 0.21243508 
  <eigenvalue_sum>  -7.64761704 </eigenvalue_sum>
  <eigenvalue_sum>  -7.64763101 </eigenvalue_sum>
  Anderson extrapolation: theta=2.76916203 (2.00000000)
  Anderson extrapolation: theta=2.67083896 (2.00000000)
  <eigenvalue_sum>  -7.64767117 </eigenvalue_sum>
  Anderson extrapolation: theta=0.63338031 (0.63338031)
  Anderson extrapolation: theta=0.63658627 (0.63658627)
  <eigenvalue_sum>  -7.64770875 </eigenvalue_sum>
  Anderson extrapolation: theta=1.18678916 (1.18678916)
  Anderson extrapolation: theta=1.45336555 (1.45336555)
  <eigenvalue_sum>  -7.64776613 </eigenvalue_sum>
  Anderson extrapolation: theta=1.29281503 (1.29281503)
  Anderson extrapolation: theta=1.25612750 (1.25612750)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35671   -21.43064   -14.23898   -14.16218   -14.16218
    -7.72844    -7.72844    -1.85169     1.75634     1.98373
     2.07339
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08388   -19.55766   -13.38159   -12.16505   -12.16505
    -5.25083    -5.25083    -1.70728     2.29771
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169063 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.54493730 -0.62812272 0.25757861 
  <eigenvalue_sum>  -7.64868383 </eigenvalue_sum>
  <eigenvalue_sum>  -7.64869677 </eigenvalue_sum>
  Anderson extrapolation: theta=2.79680869 (2.00000000)
  Anderson extrapolation: theta=3.37344815 (2.00000000)
  <eigenvalue_sum>  -7.64873468 </eigenvalue_sum>
  Anderson extrapolation: theta=1.07949488 (1.07949488)
  Anderson extrapolation: theta=1.40441140 (1.40441140)
  <eigenvalue_sum>  -7.64878810 </eigenvalue_sum>
  Anderson extrapolation: theta=1.77121481 (1.77121481)
  Anderson extrapolation: theta=1.26084188 (1.26084188)
  <eigenvalue_sum>  -7.64888910 </eigenvalue_sum>
  Anderson extrapolation: theta=1.01303308 (1.01303308)
  Anderson extrapolation: theta=1.27632049 (1.27632049)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35659   -21.43057   -14.23890   -14.16210   -14.16210
    -7.72836    -7.72836    -1.85858     1.75365     1.98241
     2.06246
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08377   -19.55758   -13.38152   -12.16497   -12.16497
    -5.25075    -5.25075    -1.71363     2.29343
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169068 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.57504020 -0.47512481 0.04278916 
  <eigenvalue_sum>  -7.64951108 </eigenvalue_sum>
  <eigenvalue_sum>  -7.64952246 </eigenvalue_sum>
  Anderson extrapolation: theta=3.87439708 (2.00000000)
  Anderson extrapolation: theta=3.91683036 (2.00000000)
  <eigenvalue_sum>  -7.64955622 </eigenvalue_sum>
  Anderson extrapolation: theta=1.63080746 (1.63080746)
  Anderson extrapolation: theta=1.46039330 (1.46039330)
  <eigenvalue_sum>  -7.64962132 </eigenvalue_sum>
  Anderson extrapolation: theta=1.20778469 (1.20778469)
  Anderson extrapolation: theta=0.97410306 (0.97410306)
  <eigenvalue_sum>  -7.64970907 </eigenvalue_sum>
  Anderson extrapolation: theta=1.87930221 (1.87930221)
  Anderson extrapolation: theta=1.97159763 (1.97159763)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35672   -21.43068   -14.23901   -14.16221   -14.16221
    -7.72847    -7.72847    -1.86235     1.75209     1.98147
     2.05151
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08390   -19.55769   -13.38162   -12.16508   -12.16508
    -5.25086    -5.25086    -1.71675     2.29139
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169070 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.72677330 0.25206324 -0.32455435 
  <eigenvalue_sum>  -7.65003697 </eigenvalue_sum>
  <eigenvalue_sum>  -7.65004749 </eigenvalue_sum>
  Anderson extrapolation: theta=4.18081688 (2.00000000)
  Anderson extrapolation: theta=4.01902457 (2.00000000)
  <eigenvalue_sum>  -7.65007870 </eigenvalue_sum>
  Anderson extrapolation: theta=1.06911362 (1.06911362)
  Anderson extrapolation: theta=0.93080817 (0.93080817)
  <eigenvalue_sum>  -7.65012185 </eigenvalue_sum>
  Anderson extrapolation: theta=0.53503171 (0.53503171)
  Anderson extrapolation: theta=0.46166964 (0.46166964)
  <eigenvalue_sum>  -7.65015491 </eigenvalue_sum>
  Anderson extrapolation: theta=3.63176855 (2.00000000)
  Anderson extrapolation: theta=3.93020984 (2.00000000)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35669   -21.43066   -14.23899   -14.16219   -14.16219
    -7.72845    -7.72845    -1.86386     1.75157     1.98126
     2.04591
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08387   -19.55767   -13.38160   -12.16506   -12.16506
    -5.25084    -5.25084    -1.71796     2.29062
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169070 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.26004964 -0.13836330 0.11113164 
  <eigenvalue_sum>  -7.65019050 </eigenvalue_sum>
  <eigenvalue_sum>  -7.65020056 </eigenvalue_sum>
  Anderson extrapolation: theta=6.02897619 (2.00000000)
  Anderson extrapolation: theta=6.59935215 (2.00000000)
  <eigenvalue_sum>  -7.65023064 </eigenvalue_sum>
  Anderson extrapolation: theta=2.06503082 (2.00000000)
  Anderson extrapolation: theta=2.23912929 (2.00000000)
  <eigenvalue_sum>  -7.65030030 </eigenvalue_sum>
  Anderson extrapolation: theta=0.65495044 (0.65495044)
  Anderson extrapolation: theta=0.67944460 (0.67944460)
  <eigenvalue_sum>  -7.65035551 </eigenvalue_sum>
  Anderson extrapolation: theta=3.83043659 (2.00000000)
  Anderson extrapolation: theta=2.91182480 (2.00000000)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35671   -21.43068   -14.23901   -14.16221   -14.16221
    -7.72847    -7.72847    -1.86337     1.75157     1.98128
     2.03873
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08389   -19.55769   -13.38162   -12.16508   -12.16508
    -5.25086    -5.25086    -1.71766     2.29062
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169070 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.55813155 -0.13731596 -0.13629343 
  <eigenvalue_sum>  -7.65060599 </eigenvalue_sum>
  <eigenvalue_sum>  -7.65061571 </eigenvalue_sum>
  Anderson extrapolation: theta=4.82177666 (2.00000000)
  Anderson extrapolation: theta=4.17241926 (2.00000000)
  <eigenvalue_sum>  -7.65064469 </eigenvalue_sum>
  Anderson extrapolation: theta=1.40720708 (1.40720708)
  Anderson extrapolation: theta=1.01078813 (1.01078813)
  <eigenvalue_sum>  -7.65069453 </eigenvalue_sum>
  Anderson extrapolation: theta=0.53223453 (0.53223453)
  Anderson extrapolation: theta=0.43468827 (0.43468827)
  <eigenvalue_sum>  -7.65073037 </eigenvalue_sum>
  Anderson extrapolation: theta=3.86502716 (2.00000000)
  Anderson extrapolation: theta=3.59608501 (2.00000000)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35672   -21.43069   -14.23902   -14.16222   -14.16222
    -7.72848    -7.72848    -1.86449     1.75120     1.98107
     2.03278
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08390   -19.55770   -13.38163   -12.16509   -12.16509
    -5.25087    -5.25087    -1.71851     2.29009
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169071 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.63792870 -0.41983766 -0.18584570 
  <eigenvalue_sum>  -7.65082431 </eigenvalue_sum>
  <eigenvalue_sum>  -7.65083370 </eigenvalue_sum>
  Anderson extrapolation: theta=7.52379183 (2.00000000)
  Anderson extrapolation: theta=7.53721200 (2.00000000)
  <eigenvalue_sum>  -7.65086178 </eigenvalue_sum>
  Anderson extrapolation: theta=2.67564284 (2.00000000)
  Anderson extrapolation: theta=2.71778091 (2.00000000)
  <eigenvalue_sum>  -7.65092690 </eigenvalue_sum>
  Anderson extrapolation: theta=1.04253064 (1.04253064)
  Anderson extrapolation: theta=0.97708402 (0.97708402)
  <eigenvalue_sum>  -7.65100347 </eigenvalue_sum>
  Anderson extrapolation: theta=2.02003113 (2.00000000)
  Anderson extrapolation: theta=1.52067172 (1.52067172)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35673   -21.43070   -14.23903   -14.16222   -14.16222
    -7.72848    -7.72848    -1.86456     1.75112     1.98102
     2.02370
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08391   -19.55771   -13.38164   -12.16509   -12.16509
    -5.25087    -5.25087    -1.71861     2.28996
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169071 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.89719588 0.06895730 -0.26881532 
  <eigenvalue_sum>  -7.65117879 </eigenvalue_sum>
  <eigenvalue_sum>  -7.65118780 </eigenvalue_sum>
  Anderson extrapolation: theta=5.31649058 (2.00000000)
  Anderson extrapolation: theta=4.55003949 (2.00000000)
  <eigenvalue_sum>  -7.65121462 </eigenvalue_sum>
  Anderson extrapolation: theta=1.41683030 (1.41683030)
  Anderson extrapolation: theta=1.03446322 (1.03446322)
  <eigenvalue_sum>  -7.65126105 </eigenvalue_sum>
  Anderson extrapolation: theta=0.38559151 (0.38559151)
  Anderson extrapolation: theta=0.30267795 (0.30267795)
  <eigenvalue_sum>  -7.65128762 </eigenvalue_sum>
  Anderson extrapolation: theta=6.27893637 (2.00000000)
  Anderson extrapolation: theta=5.74011879 (2.00000000)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35673   -21.43070   -14.23903   -14.16222   -14.16222
    -7.72849    -7.72849    -1.86468     1.75107     1.98097
     2.01907
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08391   -19.55771   -13.38164   -12.16509   -12.16509
    -5.25087    -5.25087    -1.71871     2.28988
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169071 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.39395104 0.09120885 -0.02710993 
  <eigenvalue_sum>  -7.65135399 </eigenvalue_sum>
  <eigenvalue_sum>  -7.65136269 </eigenvalue_sum>
  Anderson extrapolation: theta=9.64146080 (2.00000000)
  Anderson extrapolation: theta=9.21406301 (2.00000000)
  <eigenvalue_sum>  -7.65138867 </eigenvalue_sum>
  Anderson extrapolation: theta=3.66505427 (2.00000000)
  Anderson extrapolation: theta=3.43797239 (2.00000000)
  <eigenvalue_sum>  -7.65144893 </eigenvalue_sum>
  Anderson extrapolation: theta=1.74434027 (1.74434027)
  Anderson extrapolation: theta=1.37484452 (1.37484452)
  <eigenvalue_sum>  -7.65156136 </eigenvalue_sum>
  Anderson extrapolation: theta=1.26399275 (1.26399275)
  Anderson extrapolation: theta=0.87144574 (0.87144574)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35673   -21.43070   -14.23903   -14.16223   -14.16223
    -7.72849    -7.72849    -1.86471     1.75104     1.98092
     2.00950
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08391   -19.55771   -13.38164   -12.16510   -12.16510
    -5.25088    -5.25088    -1.71874     2.28981
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169070 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.71596141 0.08051739 -0.05752290 
  <eigenvalue_sum>  -7.65171444 </eigenvalue_sum>
  <eigenvalue_sum>  -7.65172269 </eigenvalue_sum>
  Anderson extrapolation: theta=5.23217271 (2.00000000)
  Anderson extrapolation: theta=4.20033169 (2.00000000)
  <eigenvalue_sum>  -7.65174718 </eigenvalue_sum>
  Anderson extrapolation: theta=1.33700760 (1.33700760)
  Anderson extrapolation: theta=0.82801522 (0.82801522)
  <eigenvalue_sum>  -7.65178754 </eigenvalue_sum>
  Anderson extrapolation: theta=0.34134680 (0.34134680)
  Anderson extrapolation: theta=0.17067356 (0.17067356)
  <eigenvalue_sum>  -7.65180920 </eigenvalue_sum>
  Anderson extrapolation: theta=7.17098261 (2.00000000)
  Anderson extrapolation: theta=4.18407556 (2.00000000)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35674   -21.43070   -14.23903   -14.16223   -14.16223
    -7.72849    -7.72849    -1.86474     1.75103     1.98089
     2.00557
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08391   -19.55771   -13.38164   -12.16510   -12.16510
    -5.25088    -5.25088    -1.71877     2.28978
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169071 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.19813612 0.17713745 0.14203980 
  <eigenvalue_sum>  -7.65186113 </eigenvalue_sum>
  <eigenvalue_sum>  -7.65186903 </eigenvalue_sum>
  Anderson extrapolation: theta=10.63794976 (2.00000000)
  Anderson extrapolation: theta=3.73946056 (2.00000000)
  <eigenvalue_sum>  -7.65189263 </eigenvalue_sum>
  Anderson extrapolation: theta=4.13731361 (2.00000000)
  Anderson extrapolation: theta=0.25007887 (0.25007887)
  <eigenvalue_sum>  -7.65194704 </eigenvalue_sum>
  Anderson extrapolation: theta=2.07037219 (2.00000000)
  Anderson extrapolation: theta=-1.70066397 (0.00000000)
  <eigenvalue_sum>  -7.65206203 </eigenvalue_sum>
  Anderson extrapolation: theta=1.18821867 (1.18821867)
  Anderson extrapolation: theta=-7.50138601 (0.00000000)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35674   -21.43070   -14.23903   -14.16223   -14.16223
    -7.72849    -7.72849    -1.86475     1.75102     1.98082
     1.99633
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08391   -19.55771   -13.38164   -12.16510   -12.16510
    -5.25088    -5.25088    -1.71878     2.28976
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169070 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.19183832 0.61055705 0.45856248 
  <eigenvalue_sum>  -7.65220266 </eigenvalue_sum>
  <eigenvalue_sum>  -7.65221005 </eigenvalue_sum>
  Anderson extrapolation: theta=5.14186973 (2.00000000)
  Anderson extrapolation: theta=-9.53476503 (0.00000000)
  <eigenvalue_sum>  -7.65223183 </eigenvalue_sum>
  Anderson extrapolation: theta=1.27378821 (1.27378821)
  Anderson extrapolation: theta=-13.37485408 (0.00000000)
  <eigenvalue_sum>  -7.65226629 </eigenvalue_sum>
  Anderson extrapolation: theta=0.31281427 (0.31281427)
  Anderson extrapolation: theta=-16.28545376 (0.00000000)
  <eigenvalue_sum>  -7.65228407 </eigenvalue_sum>
  Anderson extrapolation: theta=7.80868520 (2.00000000)
  Anderson extrapolation: theta=-18.80671155 (0.00000000)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35674   -21.43070   -14.23903   -14.16223   -14.16223
    -7.72849    -7.72849    -1.86475     1.75102     1.98077
     1.99302
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08391   -19.55771   -13.38164   -12.16510   -12.16510
    -5.25088    -5.25088    -1.71877     2.28976
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169071 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.03483510 -0.15823731 0.35688041 
  <eigenvalue_sum>  -7.65233065 </eigenvalue_sum>
  <eigenvalue_sum>  -7.65233766 </eigenvalue_sum>
  Anderson extrapolation: theta=11.53061250 (2.00000000)
  Anderson extrapolation: theta=-10.04170630 (0.00000000)
  <eigenvalue_sum>  -7.65235849 </eigenvalue_sum>
  Anderson extrapolation: theta=4.57191122 (2.00000000)
  Anderson extrapolation: theta=-17.71668861 (0.00000000)
  <eigenvalue_sum>  -7.65240663 </eigenvalue_sum>
  Anderson extrapolation: theta=2.37591799 (2.00000000)
  Anderson extrapolation: theta=-23.31114007 (0.00000000)
  <eigenvalue_sum>  -7.65250816 </eigenvalue_sum>
  Anderson extrapolation: theta=1.44084437 (1.44084437)
  Anderson extrapolation: theta=-27.20164322 (0.00000000)
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.35674   -21.43070   -14.23903   -14.16223   -14.16223
    -7.72849    -7.72849    -1.86477     1.75101     1.98044
     1.98444
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.08391   -19.55771   -13.38164   -12.16510   -12.16510
    -5.25088    -5.25088    -1.71880     2.28974
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.82169070 </etotal_int>
  BOSampleStepper: end scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
  <ekin>        22.00433713 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -36.46913863 </eps>
  <enl>          4.29141926 </enl>
  <ecoul>      -14.82648545 </ecoul>
  <exc>         -6.82182302 </exc>
  <esr>          1.89222900 </esr>
  <eself>       19.14922946 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -31.82169070 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -31.82169070 </enthalpy>
<atomset>
<unit_cell 
    a=" 11.00000000   0.00000000   0.00000000"
    b="  0.00000000  11.00000000   0.00000000"
    c="  0.00000000   0.00000000  11.00000000" />
  <atom name="O1" species="oxygen">
    <position> 1.16000000 0.00000000 0.00000000 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.02314905 -0.00000060 0.00000036 </force>
  </atom>
  <atom name="O2" species="oxygen">
    <position> -1.16000000 0.00000000 0.00000000 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.02315199 -0.00000041 0.00000062 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 11.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 11.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 11.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 1331.000 </unit_cell_volume>
<timing name="iteration"       min="9.179" max="9.179"/>
</iteration>
<timing name="charge"          min="0.427" max="0.433"/>
<timing name="energy"          min="4.548" max="4.564"/>
<timing name="ortho_align"     min="0.684" max="0.716"/>
<timing name="psda_prec"       min="0.030" max="0.030"/>
<timing name="psda_residual"   min="0.574" max="0.590"/>
<timing name="psda_update_wf"  min="0.057" max="0.074"/>
<timing name="update_vhxc"     min="2.440" max="2.440"/>
<timing name="wf_update"       min="1.413" max="1.433"/>
<timing name="wfdiag"          min="0.127" max="0.131"/>
<timing name="ekin"            min="0.054" max="0.070"/>
<timing name="exc"             min="2.343" max="2.344"/>
<timing name="hpsi"            min="4.363" max="4.363"/>
<timing name="nonlocal"        min="0.121" max="0.121"/>
<timing name="charge_compute"  min="0.271" max="0.277"/>
<timing name="charge_integral" min="0.019" max="0.021"/>
<timing name="charge_rowsum"   min="0.009" max="0.010"/>
<timing name="charge_vft"      min="0.126" max="0.126"/>
[qbox]  End of command stream 
<real_time> 9.334 </real_time>
<end_time> 2017-08-29T16:04:33Z </end_time>
</fpmd:simulation>
